# An example of ClusterConfig with a normal nodegroup and a Fargate profile.
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: CLUSTER_NAME
  region: REGION
  
iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: s3-reader
      namespace: eksfg-etl
    attachPolicyARNs:
    - "arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"
nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 6
    labels: { nodeType: ec2 }

fargateProfiles:
  - name: fp-etl
    selectors:
      # All workloads in the "default" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: eksfg-etl
      # All workloads in the "kube-system" Kubernetes namespace will be
      # scheduled onto Fargate:
      # - namespace: kube-system
