# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
apiVersion: v1
kind: Namespace
metadata:
  name: eksfg-etl
---
# Service endpoint
kind: Service
apiVersion: v1
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:iam::708432729963:server-certificate/testharness
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
  labels:
    k8s-app: etl-testharness
  name: etl-testharness
  namespace: eksfg-etl
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8080
  selector:
    k8s-app: etl-testharness


---
# test harness
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: etl-testharness
  name: etl-testharness
  namespace: eksfg-etl
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: etl-testharness
  template:
    metadata:
      labels:
        k8s-app: etl-testharness
    spec:
      serviceAccountName: s3-reader
      containers:
        - name: etl-testharness
          image: 708432729963.dkr.ecr.us-east-2.amazonaws.com/eksfg-test:3
          imagePullPolicy: Always
          env:
          - name: PYTHONUNBUFFERED
            value: "1"           
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 30          
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 1001
            runAsGroup: 2001
